language: node_js
node_js:
  - '0.10'
before_script:
  - sudo apt-get install -qq ruby1.9.1-dev
  - gem install sass compass
  - npm install -g bower grunt-cli
  - cd src/nih_wayfinding
  - npm install
  - bower install
