---
# Set owner to ansible ssh user because synchronize always runs as ansible_ssh_user on host
- name: Create Directory for OTP data
  file: path={{ otp_data_dir }} state=directory owner={{ansible_ssh_user}} mode=0775

- name: Copy OTP Data
  copy: src=./ dest="{{ otp_data_dir }}/" owner={{ansible_ssh_user}} group={{ansible_ssh_user}} mode=0664

- name: Run Graph Builder
  command: /usr/bin/java -Xmx{{ otp_process_mem }} -jar {{ otp_jarfile }} --build {{ otp_data_dir }}
  args:
    chdir: "{{ otp_bin_dir }}"
  notify: Restart OpenTripPlanner
  sudo: False
