---
app_home: /opt/app
app_config_home: /etc/nih-wayfinding.d/env
app_deploy_branch: "master"

app_log: /var/log/nih-wayfinding-app.log
app_log_rotate_count: 5
app_log_rotate_interval: daily

app_npm_version: 2.1.14
app_sass_version: 3.4.9

otp_ip: 33.33.33.11
otp_port: 8080
