---
- name: Install Geospatial libraries
  apt: pkg={{ item }} state=present
  with_items:
    - binutils=2.22-6ubuntu1.1
    - libproj-dev=4.7.0-1
    - gdal-bin=1.7.3-6ubuntu3

- name: Configure the main PostgreSQL APT repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release}}-pgdg main"
                  state=present

- name: Install PostgreSQL client
  apt: pkg=postgresql-client-{{ postgresql_version }}={{ postgresql_package_version }}
