---
- name: Create folders for static files
  file: path={{ item }}
        state=directory
        owner=root
        group=nih-wayfinding
        mode=0775
  with_items:
    - "{{ app_static_root }}"
    - "{{ app_media_root }}"
    - "{{ app_static_cache }}"

- name: Install Sass
  gem: name=sass
       version="{{ app_sass_version }}"
       user_install=no
       state=present

- name: Install Compass
  gem: name=compass
       user_install=no
       state=present

- name: Install grunt-cli and bower
  command: npm install -g bower grunt-cli
  args:
    chdir: "{{ app_home }}"

- name: Install application javascript dependencies (npm)
  command: npm install
  sudo: no
  args:
    chdir: "{{ app_home }}"

- name: Install application javascript dependencies (bower)
  command: bower install
  sudo: no
  args:
    chdir: "{{ app_home }}"

# Always do this, because of the junky way we're proxy passing grunt serve to /dev/ via nginx
#   we need this to be run in dev at least once so that images are in the right place
# FIXME: If we ever revisit this app, we'll want to remove this debt
- name: Create static files
  command: grunt build
  sudo: no
  args:
    chdir: "{{ app_home }}"
