---
- hosts: app-servers
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "nih-wayfinding.app" }
    - { role: "nih-wayfinding.postgresql", when: developing_or_testing }
    - { role: "nih-wayfinding.pgweb", when: developing_or_testing }
